# Site configuration

domain: "http://jekyll.chingr.com"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jekyll.chingr.com/" # the base hostname & protocol for your site
permalink: /:title/
basecss: /css/main.css
# Theme specific configuration
author: chingor
title: Jekyll Test
description: >
  This blog will document the process of building a Jeykll Site on Google Cloud Platform

# Contact and social media links
twitter_username: chingor
github_username: chingor13

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - cloudbuild.yaml

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: gcp jekyll
